# Generated by Django 4.0.1 on 2022-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=32, verbose_name='팀명')),
                ('team_yn', models.CharField(default='N', max_length=1)),
                ('yn_dttm', models.DateTimeField(auto_now_add=True, verbose_name='승인일시')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('updated_dttm', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'bs team',
                'verbose_name_plural': 'bs team',
                'db_table': 'bs_team',
            },
        ),
        migrations.CreateModel(
            name='BsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=32, verbose_name='이름')),
                ('team_name', models.CharField(max_length=32, verbose_name='팀명')),
                ('back_number', models.CharField(blank=True, max_length=3, null=True, verbose_name='등번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
                ('updated_dttm', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'bs user',
                'verbose_name_plural': 'bs user',
                'db_table': 'bs_user',
            },
        ),
    ]
