# Generated by Django 4.0.1 on 2022-01-06 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bsuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='이름')),
                ('teamname', models.CharField(max_length=32, verbose_name='팀명')),
                ('backnumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('password', models.CharField(max_length=32, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='가입일시')),
            ],
            options={
                'verbose_name': 'bs user',
                'verbose_name_plural': 'bs user',
                'db_table': 'bs_user',
            },
        ),
    ]
