# Generated by Django 4.0.1 on 2022-01-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsuser',
            options={'managed': False, 'verbose_name': 'bs user', 'verbose_name_plural': 'bs user'},
        ),
    ]
