# Generated by Django 4.0.1 on 2022-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsteam',
            name='id',
        ),
        migrations.AlterField(
            model_name='bsteam',
            name='team_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='팀명'),
        ),
    ]
