# Generated by Django 4.0.1 on 2022-01-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_bsteam_id_alter_bsteam_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsuser',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', max_length=32, on_delete=django.db.models.deletion.CASCADE, to='user.bsteam', verbose_name='팀명'),
        ),
    ]
