# Generated by Django 4.0.1 on 2022-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BsBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='아이디')),
                ('title', models.CharField(max_length=128, verbose_name='글제목')),
                ('content', models.TextField(verbose_name='글내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_dttm', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'bs board',
                'verbose_name_plural': 'bs board',
                'db_table': 'bs_board',
            },
        ),
    ]
