# Generated by Django 4.0.1 on 2022-01-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_bsboard_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsboard',
            old_name='user_id',
            new_name='bsuser',
        ),
    ]
